name: agora_mobile
description: "Agora - Decentralized P2P Voice Chat"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ffi: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
